import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

import { Button } from "../button";
import { Eye } from "lucide-react";
import { reportsMock } from "@/mocks/mocks";
import { useEffect, useRef } from "react";

interface ReportsTableProps {
  reports: typeof reportsMock;
}

export function ReportsTable({
  reports,
}: ReportsTableProps) {
  const tableRef = useRef<HTMLDivElement | null>(null);

  return (
    <div
      ref={tableRef}
      className="rounded-lg border bg-white max-h-[420px] overflow-y-auto"
    >
      <Table className="w-full">
        <TableHeader className="sticky top-0 z-10 bg-white">
          <TableRow>
            <TableHead className="px-4 py-3">Report Name</TableHead>
            <TableHead className="px-4 py-3">Date Generated</TableHead>
            <TableHead className="px-4 py-3">Generated By</TableHead>
            <TableHead className="px-4 py-3 text-center">Status</TableHead>
            <TableHead className="px-4 py-3 text-center">Actions</TableHead>
          </TableRow>
        </TableHeader>

        <TableBody>
          {reports.map((report) => {
            return (
              <TableRow>

                <TableCell className="px-4 py-3 text-sm font-medium text-slate-700">
                 {report.name}
                </TableCell>
                
                <TableCell className="px-4 py-3 text-sm text-left text-slate-600">
                 {report.date}
                </TableCell>
                
                <TableCell className="px-4 py-3 text-sm text-left text-slate-600">
                 {report.by}
                </TableCell>

                <TableCell className="px-4 py-3 text-sm text-center text-slate-600">
                 {report.status}
                </TableCell>

                <TableCell className="px-4 py-3 text-sm text-center text-slate-600">
                   <Button
                      variant="ghost"
                      size="sm"
                      className="text-[#e60028] hover:text-[#b8001f] hover:bg-red-50"
                    >
                      <Eye className="w-4 h-4 mr-1" />
                      View
                    </Button>
                </TableCell>
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
    </div>
  );
}
