// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ubs.Monitoring.Infrastructure.Persistence;

#nullable disable

namespace Ubs.Monitoring.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "account_status", "account_status", new[] { "active", "blocked", "closed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "account_type", "account_type", new[] { "checking", "savings", "investment", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "audit_action", "audit_action", new[] { "create", "update", "delete" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "case_decision", "case_decision", new[] { "fraudulent", "not_fraudulent", "inconclusive" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "case_status", "case_status", new[] { "new", "under_review", "resolved" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "identifier_type", "identifier_type", new[] { "cpf", "cnpj", "tax_id", "passport", "lei", "pix_email", "pix_phone", "pix_random", "iban", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "kyc_status", "kyc_status", new[] { "pending", "verified", "expired", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "legal_type", "legal_type", new[] { "individual", "corporate" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "risk_level", "risk_level", new[] { "low", "medium", "high" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "rule_type", "rule_type", new[] { "daily_limit", "banned_countries", "banned_accounts", "structuring" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "severity", "severity", new[] { "low", "medium", "high", "critical" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transaction_type", "transaction_type", new[] { "deposit", "withdrawal", "transfer" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transfer_method", "transfer_method", new[] { "pix", "ted", "wire" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountIdentifier")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AccountIdentifier")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.AccountIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IdentifierType")
                        .HasColumnType("integer");

                    b.Property<string>("IdentifierValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IssuedCountryCode")
                        .HasColumnType("char(2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("IdentifierType", "IdentifierValue")
                        .IsUnique()
                        .HasDatabaseName("ux_unique_routing_identifiers")
                        .HasFilter("\"IdentifierType\" IN (5, 6, 7, 8)");

                    b.ToTable("account_identifiers", (string)null);
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Analyst", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CorporateEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ProfilePictureBase64")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorporateEmail")
                        .IsUnique();

                    b.ToTable("analysts", (string)null);
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("PerformedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PerformedByAnalystId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PerformedAtUtc")
                        .HasDatabaseName("ix_audit_performed_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entity");

                    b.HasIndex("PerformedByAnalystId", "PerformedAtUtc")
                        .HasDatabaseName("ix_audit_by_analyst_time");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalystId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Decision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AnalystId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_cases_updated");

                    b.HasIndex("ClientId", "OpenedAtUtc")
                        .HasDatabaseName("ix_cases_client_opened");

                    b.HasIndex("Status", "Severity")
                        .HasDatabaseName("ix_cases_status_severity");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.CaseFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_case_findings_case");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_case_findings_rule");

                    b.ToTable("case_findings", (string)null);
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<JsonDocument>("AddressJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("KycStatus")
                        .HasColumnType("integer");

                    b.Property<int>("LegalType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_clients_country");

                    b.HasIndex("KycStatus")
                        .HasDatabaseName("ix_clients_kyc_status");

                    b.HasIndex("RiskLevel")
                        .HasDatabaseName("ix_clients_risk_level");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.ComplianceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_rules_updated");

                    b.HasIndex("RuleType", "IsActive")
                        .HasDatabaseName("ix_rules_type_active");

                    b.ToTable("compliance_rules", (string)null);
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("RiskLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("risk_level");

                    b.HasKey("Code");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_countries_name");

                    b.HasIndex("RiskLevel")
                        .HasDatabaseName("IX_countries_risk_level");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "AR",
                            Name = "Argentina",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "BR",
                            Name = "Brazil",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "CA",
                            Name = "Canada",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "CL",
                            Name = "Chile",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "CO",
                            Name = "Colombia",
                            RiskLevel = 1
                        },
                        new
                        {
                            Code = "MX",
                            Name = "Mexico",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "US",
                            Name = "United States",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "UY",
                            Name = "Uruguay",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "VE",
                            Name = "Venezuela",
                            RiskLevel = 2
                        },
                        new
                        {
                            Code = "PE",
                            Name = "Peru",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "EC",
                            Name = "Ecuador",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "BO",
                            Name = "Bolivia",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "AT",
                            Name = "Austria",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "BE",
                            Name = "Belgium",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "CH",
                            Name = "Switzerland",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "DE",
                            Name = "Germany",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "DK",
                            Name = "Denmark",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "ES",
                            Name = "Spain",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "FI",
                            Name = "Finland",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "FR",
                            Name = "France",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "GB",
                            Name = "United Kingdom",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "GR",
                            Name = "Greece",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "IE",
                            Name = "Ireland",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "IT",
                            Name = "Italy",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "NL",
                            Name = "Netherlands",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "NO",
                            Name = "Norway",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "PL",
                            Name = "Poland",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "PT",
                            Name = "Portugal",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "RU",
                            Name = "Russia",
                            RiskLevel = 2
                        },
                        new
                        {
                            Code = "SE",
                            Name = "Sweden",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "CN",
                            Name = "China",
                            RiskLevel = 1
                        },
                        new
                        {
                            Code = "IN",
                            Name = "India",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "ID",
                            Name = "Indonesia",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "JP",
                            Name = "Japan",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "KR",
                            Name = "South Korea",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "MY",
                            Name = "Malaysia",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "PH",
                            Name = "Philippines",
                            RiskLevel = 1
                        },
                        new
                        {
                            Code = "SG",
                            Name = "Singapore",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "TH",
                            Name = "Thailand",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "VN",
                            Name = "Vietnam",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "KP",
                            Name = "North Korea",
                            RiskLevel = 2
                        },
                        new
                        {
                            Code = "IR",
                            Name = "Iran",
                            RiskLevel = 2
                        },
                        new
                        {
                            Code = "AE",
                            Name = "United Arab Emirates",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "IL",
                            Name = "Israel",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "SA",
                            Name = "Saudi Arabia",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "SY",
                            Name = "Syria",
                            RiskLevel = 2
                        },
                        new
                        {
                            Code = "EG",
                            Name = "Egypt",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "ZA",
                            Name = "South Africa",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "NG",
                            Name = "Nigeria",
                            RiskLevel = 1
                        },
                        new
                        {
                            Code = "KE",
                            Name = "Kenya",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "AU",
                            Name = "Australia",
                            RiskLevel = 0
                        },
                        new
                        {
                            Code = "NZ",
                            Name = "New Zealand",
                            RiskLevel = 0
                        });
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.FxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("QuoteCurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyCode", "QuoteCurrencyCode", "AsOfUtc")
                        .IsUnique()
                        .HasDatabaseName("ux_fx_rates_base_quote_asof");

                    b.ToTable("fx_rates", (string)null);
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("CpAccount")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CpBank")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CpBranch")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CpCountryCode")
                        .HasColumnType("char(2)");

                    b.Property<string>("CpIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("CpIdentifierType")
                        .HasColumnType("integer");

                    b.Property<string>("CpName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<Guid?>("FxRateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TransferMethod")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Transactions_AccountId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_Transactions_ClientId");

                    b.HasIndex("CpCountryCode")
                        .HasDatabaseName("IX_Transactions_CpCountryCode");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("IX_Transactions_CurrencyCode");

                    b.HasIndex("FxRateId");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_Transactions_OccurredAtUtc");

                    b.HasIndex("TransferMethod")
                        .HasDatabaseName("IX_Transactions_TransferMethod");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Transactions_Type");

                    b.HasIndex("AccountId", "OccurredAtUtc")
                        .HasDatabaseName("IX_Transactions_AccountId_OccurredAtUtc");

                    b.HasIndex("ClientId", "OccurredAtUtc")
                        .HasDatabaseName("IX_Transactions_ClientId_OccurredAtUtc");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("chk_transfer_required_fields", "\r\n                    (\"Type\" <> 2)\r\n                    OR (\r\n                        \"TransferMethod\" IS NOT NULL\r\n                        AND \"CpCountryCode\" IS NOT NULL\r\n                        AND \"CpIdentifierType\" IS NOT NULL\r\n                        AND \"CpIdentifier\" IS NOT NULL\r\n                    )\r\n                    ");
                        });
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Account", b =>
                {
                    b.HasOne("Ubs.Monitoring.Domain.Entities.Client", "Client")
                        .WithMany("Accounts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.AccountIdentifier", b =>
                {
                    b.HasOne("Ubs.Monitoring.Domain.Entities.Account", "Account")
                        .WithMany("Identifiers")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Ubs.Monitoring.Domain.Entities.Analyst", "PerformedByAnalyst")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedByAnalystId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformedByAnalyst");
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Case", b =>
                {
                    b.HasOne("Ubs.Monitoring.Domain.Entities.Account", "Account")
                        .WithMany("Cases")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ubs.Monitoring.Domain.Entities.Analyst", "Analyst")
                        .WithMany("Cases")
                        .HasForeignKey("AnalystId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ubs.Monitoring.Domain.Entities.Client", "Client")
                        .WithMany("Cases")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ubs.Monitoring.Domain.Entities.Transaction", "Transaction")
                        .WithOne("Case")
                        .HasForeignKey("Ubs.Monitoring.Domain.Entities.Case", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Analyst");

                    b.Navigation("Client");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.CaseFinding", b =>
                {
                    b.HasOne("Ubs.Monitoring.Domain.Entities.Case", "Case")
                        .WithMany("Findings")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ubs.Monitoring.Domain.Entities.ComplianceRule", "Rule")
                        .WithMany("CaseFindings")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Client", b =>
                {
                    b.HasOne("Ubs.Monitoring.Domain.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Ubs.Monitoring.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ubs.Monitoring.Domain.Entities.Client", "Client")
                        .WithMany("Transactions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ubs.Monitoring.Domain.Entities.FxRate", "FxRate")
                        .WithMany()
                        .HasForeignKey("FxRateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Client");

                    b.Navigation("FxRate");
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Account", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Identifiers");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Analyst", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Cases");
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Case", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Client", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Cases");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.ComplianceRule", b =>
                {
                    b.Navigation("CaseFindings");
                });

            modelBuilder.Entity("Ubs.Monitoring.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Case");
                });
#pragma warning restore 612, 618
        }
    }
}
